# OasisFarm Configuration File

farm-check-interval: 100

farms:
  starter_zone:
    entry-cooldown: 60
    region:
      world: "world"
      pos1: "100,64,100"
      pos2: "200,80,200"
    max-mobs: 50
    mobs:
      # Mob templates are now defined in mob-templates.yml
      # Format is: <template_id>: <spawn_chance>
      starter_zombie: 0.80
      starter_skeleton: 0.20