# OasisFarm Main Configuration File (V4.5)

# How often the plugin's main spawner ticks (in server ticks). 20 ticks = 1 second.
# This is a base value; events can modify it temporarily.
farm-check-interval: 100

farms:
  starter_zone:
    # Cooldown in seconds before a player can re-enter this farm region.
    entry-cooldown: 60

    # The physical boundaries of the farm.
    region:
      world: "world"
      pos1: "100,64,100"
      pos2: "200,80,200"

    # The maximum number of mobs allowed in this farm at one time.
    max-mobs: 50

    # List of mobs that can spawn here.
    # Format is: <template_id_from_mob-templates.yml>: <spawn_chance_decimal>
    mobs:
      starter_zombie: 0.80
      starter_skeleton: 0.20
    hologram-template: "default-farm-hologram"
    possible-events:
      - 'blood_moon' # The ID must match an event in events.yml

  boss_arena:
    entry-cooldown: 300
    region:
      world: "world"
      pos1: "500,64,500"
      pos2: "550,80,550"
    max-mobs: 1
    mobs:
      undead_king: 1.0
    hologram-template: "boss-arena-hologram"
    possible-events:
      - 'blood_moon' # The ID must match an event in events.yml