name: OasisFarm
version: ${project.version}
main: com.hybridiize.oasisfarm.Oasisfarm
api-version: '1.21'

# This tells the server that PlaceholderAPI is a REQUIRED dependency.
# OasisFarm will not start without it.
depend:
  - PlaceholderAPI

# This tells the server about optional dependencies.
# OasisFarm will still start if these are missing.
softdepend:
  - DecentHolograms
  - Vault
  - MythicMobs

commands:
  oasisfarm:
    description: Main command for the OasisFarm plugin.
    aliases: [of]
    permission: oasisfarm.admin