name: OasisFarm
version: ${project.version}

main: com.hybridiize.oasisfarm.Oasisfarm

api-version: '1.21'

# This section tells the server to load these plugins before OasisFarm.
softdepend:
  - PlaceholderAPI
  - DecentHolograms
  - Vault
  - MythicMobs

commands:
  oasisfarm:
    description: Main command for the OasisFarm plugin.
    aliases: [of]
    permission: oasisfarm.admin